# Generated by Django 3.1.3 on 2020-11-05 16:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('headquarters_address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('workplaces_quantity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photocenter.photocenter')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoStand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=250)),
                ('workplaces_quantity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photocenter.photooffice')),
            ],
        ),
    ]
