# Generated by Django 3.1.3 on 2020-11-06 19:18

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photocenter', '0002_auto_20201105_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos_from_each_frame_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('photos_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('paper_format', models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('A8', 'A8'), ('A9', 'A9'), ('A10', 'A10')], max_length=250)),
                ('paper_type', models.CharField(choices=[('MATTE', 'Matte'), ('GLOSSY', 'Glossy'), ('SEMI_GLOSSY', 'Semi-Glossy'), ('SUPERGLOSSY', 'SuperGlossy'), ('SILK', 'Silk'), ('SATIN', 'Satin')], max_length=250)),
                ('priority', models.CharField(choices=[('URGENT_PRIORITY', 'Urgent priority'), ('ORDINARY_PRIORITY', 'Ordinary priority')], max_length=250)),
                ('term', models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 18, 25, 171451))),
                ('photo_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photocenter.photooffice')),
                ('photo_stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photocenter.photostand')),
            ],
        ),
    ]
