# Generated by Django 3.1.3 on 2020-11-06 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photocenter', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='photo_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photocenter.photooffice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='photo_stand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photocenter.photostand'),
        ),
        migrations.AlterField(
            model_name='order',
            name='term',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 44, 8, 789692)),
        ),
    ]
