# Generated by Django 3.1.3 on 2020-11-06 19:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photocenter', '0004_auto_20201106_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='photo_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photocenter.photooffice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='photo_stand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photocenter.photostand'),
        ),
        migrations.AlterField(
            model_name='order',
            name='term',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 45, 51, 270282)),
        ),
    ]
