# Generated by Django 3.1.3 on 2020-11-08 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photocenter', '0005_auto_20201106_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('CAMERA', 'Camera'), ('LENSES', 'Lenses'), ('OUTBREAKS', 'Outbreaks'), ('PHOTO_PAPER', 'Photo paper'), ('CAMERA_ROLL', 'Camera roll'), ('PHOTOGRAPHIC_REAGENTS', 'Photographic reagents'), ('ALBUM', 'Album')], max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=250)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photocenter.item')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='paper_format',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('A8', 'A8'), ('A9', 'A9'), ('A10', 'A10')], max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='paper_type',
            field=models.CharField(choices=[('MATTE', 'Matte'), ('GLOSSY', 'Glossy'), ('SEMI_GLOSSY', 'Semi-Glossy'), ('SUPERGLOSSY', 'SuperGlossy'), ('SILK', 'Silk'), ('SATIN', 'Satin')], max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('URGENT_PRIORITY', 'Urgent priority'), ('ORDINARY_PRIORITY', 'Ordinary priority')], max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='term',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 13, 14, 1, 700903)),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('items', models.ManyToManyField(through='photocenter.ItemProvider', to='photocenter.Item')),
            ],
        ),
        migrations.AddField(
            model_name='itemprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photocenter.provider'),
        ),
        migrations.AddField(
            model_name='item',
            name='providers',
            field=models.ManyToManyField(through='photocenter.ItemProvider', to='photocenter.Provider'),
        ),
    ]
