# Generated by Django 3.1.3 on 2020-11-08 19:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photocenter', '0006_auto_20201108_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('PASSPORT_PHOTO', 'Passport photo'), ('PHOTO_RESTORATION', 'Photo restoration'), ('CAMERA_RENTAL', 'Camera rental'), ('ART_PHOTO', 'Art photo'), ('PROFESSIONAL_PHOTOGRAPHER', 'Professional photographer')], max_length=120)),
                ('photo_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photocenter.photooffice')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PROFESSIONAL', 'professional'), ('FAN', 'FAN')], max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='term',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 19, 20, 40, 453671)),
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photocenter.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photocenter.item')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalServicesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photocenter.additionalservice')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photocenter.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photocenter.customer'),
        ),
    ]
