# Generated by Django 3.1.3 on 2020-11-09 16:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photocenter', '0007_auto_20201108_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservicesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photocenter.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('PROFESSIONAL', 'Professional'), ('FAN', 'Fan')], max_length=120),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photocenter.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photocenter.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='term',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 16, 27, 49, 810390)),
        ),
    ]
