# Generated by Django 3.1.3 on 2020-11-09 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photocenter', '0008_auto_20201109_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='term',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 16, 53, 56, 71337)),
        ),
    ]
