# Generated by Django 3.1.3 on 2020-11-09 17:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photocenter', '0009_auto_20201109_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photocenter.photooffice'),
        ),
        migrations.AddField(
            model_name='item',
            name='photo_stand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photocenter.photostand'),
        ),
        migrations.AlterField(
            model_name='order',
            name='term',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 17, 20, 22, 111587)),
        ),
    ]
